export type AlertSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';

export type AlertStatus = 'ACTIVE' | 'ACKNOWLEDGED' | 'RESOLVED' | 'SNOOZED';

export type AlertType =
  | 'Bin Overflow'
  | 'Predicted Overflow'
  | 'High Fill Level'
  | 'Abnormal Fill Increase'
  | 'Bin Offline'
  | 'Sensor Battery Low'
  | 'Sensor Malfunction'
  | 'Route Delayed'
  | 'Route Deviation'
  | 'Route Stop Skipped'
  | 'Route Capacity Conflict'
  | 'Route Optimization Required'
  | 'Vehicle Capacity Near Limit'
  | 'Vehicle Offline'
  | 'Vehicle Maintenance Due'
  | 'Vehicle Route Deviation'
  | 'Missed Collection'
  | 'Overdue Collection'
  | 'High-Priority Collection Pending'
  | 'Waste Generation Spike'
  | 'Unusual Waste Pattern'
  | 'High-Demand Zone Prediction'
  | 'Prediction Service Update'
  | 'Sensor Connectivity Issue'
  | 'Data Synchronization Issue'
  | 'System Health Warning';

export type AlertSource =
  | 'AI Prediction'
  | 'Sensor'
  | 'Route Engine'
  | 'Vehicle System'
  | 'Admin/System'
  | 'System';

export type AlertEntityType = 'BIN' | 'VEHICLE' | 'ROUTE' | 'ZONE' | 'SENSOR' | 'SYSTEM';

export interface AlertMetadata {
  currentFill?: number;
  predictedFill?: number;
  predictedOverflowTime?: string;
  confidenceScore?: number;
  fillRatePerHour?: number;
  historicalAvgRate?: number;
  vehicleCapacityKg?: number;
  vehicleCurrentLoadKg?: number;
  routeDelayMinutes?: number;
  scheduledStopsCount?: number;
  completedStopsCount?: number;
  sensorBatteryPercent?: number;
  lastSignalTimestamp?: string;
  assignedDriver?: string;
  assignedVehicleId?: string;
  affectedZone?: string;
}

export interface AlertItem {
  id: string; // e.g. ALT-2026-01087
  severity: AlertSeverity;
  type: AlertType;
  title: string;
  description: string;
  source: AlertSource;
  entityType: AlertEntityType;
  entityId: string;
  location: string;
  zone: string;
  status: AlertStatus;
  isRead: boolean;
  createdAt: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  snoozedUntil?: string;
  resolutionNote?: string;
  recommendedAction: string;
  aiGenerated: boolean;
  metadata: AlertMetadata;
  activityLog?: Array<{
    timestamp: string;
    description: string;
    actor?: string;
  }>;
}

export const initialAlerts: AlertItem[] = [
  {
    id: 'ALT-2026-01087',
    severity: 'CRITICAL',
    type: 'Predicted Overflow',
    title: 'Predicted Bin Overflow at Central Market',
    description: 'BIN-1087 is expected to exceed the 95% threshold within 2 hours based on rapid fill acceleration.',
    source: 'AI Prediction',
    entityType: 'BIN',
    entityId: 'BIN-1087',
    location: 'Central Market, Gate 3',
    zone: 'Central Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '10 min ago',
    recommendedAction: 'Dispatch vehicle VEH-001 or add BIN-1087 to active collection route RT-024 immediately.',
    aiGenerated: true,
    metadata: {
      currentFill: 92,
      predictedFill: 97,
      predictedOverflowTime: '2h 10m',
      confidenceScore: 91,
      fillRatePerHour: 14,
      historicalAvgRate: 8,
      affectedZone: 'Central Zone'
    },
    activityLog: [
      { timestamp: '10 min ago', description: 'Alert generated by WasteWise AI Predictive Engine', actor: 'AI System' },
      { timestamp: '8 min ago', description: 'Automated notification dispatched to Central Zone Supervisor', actor: 'System' }
    ]
  },
  {
    id: 'ALT-2026-01088',
    severity: 'CRITICAL',
    type: 'Vehicle Offline',
    title: 'Telemetry Signal Lost for VEH-018',
    description: 'Collection vehicle VEH-018 (Tipper 04) lost telemetry and GPS signal over 42 minutes ago during active route.',
    source: 'Vehicle System',
    entityType: 'VEHICLE',
    entityId: 'VEH-018',
    location: 'South Industrial Corridor',
    zone: 'South Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '18 min ago',
    recommendedAction: 'Contact field driver Suresh Kumar directly and verify vehicle status or assign backup vehicle.',
    aiGenerated: false,
    metadata: {
      assignedDriver: 'Suresh Kumar',
      lastSignalTimestamp: '42 min ago',
      assignedVehicleId: 'VEH-018',
      affectedZone: 'South Zone'
    },
    activityLog: [
      { timestamp: '18 min ago', description: 'Vehicle heartbeat timeout threshold exceeded (30 min max)', actor: 'Vehicle Telemetry' }
    ]
  },
  {
    id: 'ALT-2026-01089',
    severity: 'CRITICAL',
    type: 'Vehicle Capacity Near Limit',
    title: 'Vehicle VEH-007 Exceeded 90% Capacity',
    description: 'EcoCompactor VEH-007 is at 92% capacity (1104 / 1200 kg) with 5 collection stops remaining.',
    source: 'Vehicle System',
    entityType: 'VEHICLE',
    entityId: 'VEH-007',
    location: 'North Commercial Loop',
    zone: 'North Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '25 min ago',
    recommendedAction: 'Reroute VEH-007 to Central Transfer Station for unloading before continuing stops.',
    aiGenerated: false,
    metadata: {
      vehicleCapacityKg: 1200,
      vehicleCurrentLoadKg: 1104,
      assignedDriver: 'Vikram Singh',
      assignedVehicleId: 'VEH-007',
      affectedZone: 'North Zone'
    },
    activityLog: [
      { timestamp: '25 min ago', description: 'Scale payload sensor reported 1104 kg', actor: 'Payload Sensor' }
    ]
  },
  {
    id: 'ALT-2026-01090',
    severity: 'CRITICAL',
    type: 'Route Delayed',
    title: 'Route RT-021 Significantly Delayed',
    description: 'Route RT-021 is running 28 minutes behind schedule due to high traffic volume on West Avenue.',
    source: 'Route Engine',
    entityType: 'ROUTE',
    entityId: 'RT-021',
    location: 'West Avenue Highway',
    zone: 'West Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '32 min ago',
    recommendedAction: 'Re-optimize RT-024 sequence or reassign 3 remaining stops to available vehicle VEH-002.',
    aiGenerated: true,
    metadata: {
      routeDelayMinutes: 28,
      scheduledStopsCount: 16,
      completedStopsCount: 7,
      assignedDriver: 'Neha Shah',
      assignedVehicleId: 'VEH-002',
      affectedZone: 'West Zone'
    },
    activityLog: [
      { timestamp: '32 min ago', description: 'ETA recalculation flagged >25 min deviation', actor: 'OR-Tools Engine' }
    ]
  },
  {
    id: 'ALT-2026-01091',
    severity: 'HIGH',
    type: 'Waste Generation Spike',
    title: 'Waste Generation Spike in Industrial Zone',
    description: 'AI model detected a 42% surge in bin fill rates across Industrial Zone Sector 4.',
    source: 'AI Prediction',
    entityType: 'ZONE',
    entityId: 'ZONE-IND',
    location: 'Industrial Sector 4',
    zone: 'Industrial Zone',
    status: 'ACKNOWLEDGED',
    isRead: true,
    createdAt: '45 min ago',
    acknowledgedAt: '30 min ago',
    recommendedAction: 'Schedule additional evening collection shift for Industrial Zone Sector 4.',
    aiGenerated: true,
    metadata: {
      confidenceScore: 94,
      fillRatePerHour: 22,
      historicalAvgRate: 11,
      affectedZone: 'Industrial Zone'
    }
  },
  {
    id: 'ALT-2026-01092',
    severity: 'HIGH',
    type: 'Vehicle Maintenance Due',
    title: 'Maintenance Overdue for Tipper VEH-013',
    description: 'Routine 10,000 km hydraulic maintenance for VEH-013 is 3 days overdue.',
    source: 'Vehicle System',
    entityType: 'VEHICLE',
    entityId: 'VEH-013',
    location: 'Central Depot Yard',
    zone: 'Central Zone',
    status: 'ACKNOWLEDGED',
    isRead: true,
    createdAt: '1h ago',
    acknowledgedAt: '40 min ago',
    recommendedAction: 'Schedule depot maintenance slot and assign replacement truck.',
    aiGenerated: false,
    metadata: {
      assignedVehicleId: 'VEH-013',
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01093',
    severity: 'HIGH',
    type: 'Bin Offline',
    title: 'Smart Sensor Telemetry Lost: BIN-1142',
    description: 'Ultrasonic fill sensor at BIN-1142 has stopped sending heartbeat packets for 35 min.',
    source: 'Sensor',
    entityType: 'BIN',
    entityId: 'BIN-1142',
    location: 'Residential Park Gate B',
    zone: 'East Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '50 min ago',
    recommendedAction: 'Dispatch IoT technician to verify sensor battery and gateway connection.',
    aiGenerated: false,
    metadata: {
      currentFill: 64,
      lastSignalTimestamp: '35 min ago',
      affectedZone: 'East Zone'
    }
  },
  {
    id: 'ALT-2026-01094',
    severity: 'MEDIUM',
    type: 'High Fill Level',
    title: 'BIN-1052 Reached 85% Fill Level',
    description: 'BIN-1052 at Civic Center is at 85% capacity and approaching overflow limit.',
    source: 'Sensor',
    entityType: 'BIN',
    entityId: 'BIN-1052',
    location: 'Civic Center Complex',
    zone: 'Central Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '1h 15m ago',
    recommendedAction: 'Add to upcoming afternoon collection cycle.',
    aiGenerated: false,
    metadata: {
      currentFill: 85,
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01095',
    severity: 'MEDIUM',
    type: 'Route Stop Skipped',
    title: 'Stop BIN-104 Skipped on Route RT-024',
    description: 'Driver Arjun Patel marked stop BIN-104 as inaccessible due to temporary road blocking.',
    source: 'Route Engine',
    entityType: 'ROUTE',
    entityId: 'RT-024',
    location: 'College Road Turn 4',
    zone: 'North Zone',
    status: 'ACKNOWLEDGED',
    isRead: true,
    createdAt: '1h 30m ago',
    acknowledgedAt: '1h 10m ago',
    recommendedAction: 'Schedule retry collection after road access is cleared.',
    aiGenerated: false,
    metadata: {
      assignedDriver: 'Arjun Patel',
      assignedVehicleId: 'VEH-001',
      affectedZone: 'North Zone'
    }
  },
  {
    id: 'ALT-2026-01096',
    severity: 'MEDIUM',
    type: 'Sensor Battery Low',
    title: 'Sensor Battery Below 15%: BIN-1204',
    description: 'IoT ultrasonic sensor battery at BIN-1204 is at 12% remaining life.',
    source: 'Sensor',
    entityType: 'BIN',
    entityId: 'BIN-1204',
    location: 'West Plaza Cinema Entrance',
    zone: 'West Zone',
    status: 'SNOOZED',
    isRead: true,
    createdAt: '2h ago',
    snoozedUntil: 'Tomorrow 09:00 AM',
    recommendedAction: 'Replace CR123A battery during next field maintenance run.',
    aiGenerated: false,
    metadata: {
      sensorBatteryPercent: 12,
      affectedZone: 'West Zone'
    }
  },
  {
    id: 'ALT-2026-01097',
    severity: 'LOW',
    type: 'Abnormal Fill Increase',
    title: 'Minor Fill Spike: BIN-1099',
    description: 'Unexpected 15% fill jump in 10 minutes recorded at Food Court Bin 02.',
    source: 'Sensor',
    entityType: 'BIN',
    entityId: 'BIN-1099',
    location: 'Food Court Plaza',
    zone: 'Central Zone',
    status: 'RESOLVED',
    isRead: true,
    createdAt: '3h ago',
    resolvedAt: '2h ago',
    resolutionNote: 'Inspected bin; bulk packaging deposited. Fill stabilized at 60%.',
    recommendedAction: 'No immediate action required; monitor trend.',
    aiGenerated: false,
    metadata: {
      currentFill: 60,
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01098',
    severity: 'LOW',
    type: 'High-Demand Zone Prediction',
    title: 'Weekend Event Waste Increase Expected',
    description: 'AI model projects 25% higher waste volume near Stadium Grounds tomorrow.',
    source: 'AI Prediction',
    entityType: 'ZONE',
    entityId: 'ZONE-STAD',
    location: 'Sports Stadium Sector',
    zone: 'South Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '3h 30m ago',
    recommendedAction: 'Pre-allocate 2 extra mini collection vehicles for weekend shift.',
    aiGenerated: true,
    metadata: {
      confidenceScore: 88,
      affectedZone: 'South Zone'
    }
  },
  {
    id: 'ALT-2026-01099',
    severity: 'INFO',
    type: 'Data Synchronization Issue',
    title: 'Telemetry Sync Complete for Zone North',
    description: 'All 142 smart bin sensors in North Zone synced successfully with cloud portal.',
    source: 'Admin/System',
    entityType: 'SYSTEM',
    entityId: 'SYS-SYNC-01',
    location: 'System Infrastructure',
    zone: 'North Zone',
    status: 'RESOLVED',
    isRead: true,
    createdAt: '4h ago',
    resolvedAt: '3h 50m ago',
    resolutionNote: 'System synchronization verified cleanly.',
    recommendedAction: 'System operating normally.',
    aiGenerated: false,
    metadata: {
      affectedZone: 'North Zone'
    }
  },
  {
    id: 'ALT-2026-01100',
    severity: 'INFO',
    type: 'Prediction Service Update',
    title: 'WasteWise AI Model Retrained v2.4',
    description: 'Seasonal fill forecasting model retrained with 98.4% validation accuracy.',
    source: 'AI Prediction',
    entityType: 'SYSTEM',
    entityId: 'AI-MODEL-v24',
    location: 'Cloud AI Engine',
    zone: 'Central Zone',
    status: 'RESOLVED',
    isRead: true,
    createdAt: '5h ago',
    resolvedAt: '4h 50m ago',
    resolutionNote: 'New AI weights deployed.',
    recommendedAction: 'View model performance metrics in Predictions module.',
    aiGenerated: true,
    metadata: {
      confidenceScore: 98.4,
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01101',
    severity: 'HIGH',
    type: 'Predicted Overflow',
    title: 'Predicted Overflow at Bus Terminal BIN-1120',
    description: 'BIN-1120 is predicted to reach 100% capacity by 01:30 PM due to peak commuter traffic.',
    source: 'AI Prediction',
    entityType: 'BIN',
    entityId: 'BIN-1120',
    location: 'Central Bus Terminal, Bay 4',
    zone: 'Central Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '22 min ago',
    recommendedAction: 'Dispatch EcoMini collection truck to service Bus Terminal bins.',
    aiGenerated: true,
    metadata: {
      currentFill: 88,
      predictedFill: 100,
      predictedOverflowTime: '1h 45m',
      confidenceScore: 93,
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01102',
    severity: 'MEDIUM',
    type: 'Route Deviation',
    title: 'Route Deviation Detected for RT-019',
    description: 'Vehicle EcoMini 03 deviated 1.2 km from designated route RT-019.',
    source: 'Route Engine',
    entityType: 'ROUTE',
    entityId: 'RT-019',
    location: 'East Outer Ring Road',
    zone: 'East Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '40 min ago',
    recommendedAction: 'Check with driver Rohan Patel for traffic detour details.',
    aiGenerated: false,
    metadata: {
      assignedDriver: 'Rohan Patel',
      assignedVehicleId: 'VEH-004',
      affectedZone: 'East Zone'
    }
  },
  {
    id: 'ALT-2026-01103',
    severity: 'HIGH',
    type: 'Missed Collection',
    title: 'Missed Scheduled Collection: BIN-1012',
    description: 'BIN-1012 in Residential Zone Sector 2 was missed during morning collection route.',
    source: 'Admin/System',
    entityType: 'BIN',
    entityId: 'BIN-1012',
    location: 'Residential Block C',
    zone: 'Residential Zone',
    status: 'ACKNOWLEDGED',
    isRead: true,
    createdAt: '1h 10m ago',
    acknowledgedAt: '50 min ago',
    recommendedAction: 'Assign spot collection crew to service missed bin.',
    aiGenerated: false,
    metadata: {
      currentFill: 89,
      affectedZone: 'Residential Zone'
    }
  },
  {
    id: 'ALT-2026-01104',
    severity: 'LOW',
    type: 'Sensor Battery Low',
    title: 'Low Battery Warning: BIN-1304',
    description: 'Ultrasonic sensor battery level dropped below 20% at BIN-1304.',
    source: 'Sensor',
    entityType: 'BIN',
    entityId: 'BIN-1304',
    location: 'South Park Promenade',
    zone: 'South Zone',
    status: 'RESOLVED',
    isRead: true,
    createdAt: '6h ago',
    resolvedAt: '1h ago',
    resolutionNote: 'Battery replaced by technician.',
    recommendedAction: 'Battery replacement completed.',
    aiGenerated: false,
    metadata: {
      sensorBatteryPercent: 18,
      affectedZone: 'South Zone'
    }
  },
  {
    id: 'ALT-2026-01105',
    severity: 'MEDIUM',
    type: 'System Health Warning',
    title: 'Gateway Packet Retries Elevated',
    description: 'LoRaWAN gateway in West Zone reporting 8.2% packet retry rate.',
    source: 'System',
    entityType: 'SYSTEM',
    entityId: 'GW-WEST-02',
    location: 'West Telecom Tower',
    zone: 'West Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '1h 40m ago',
    recommendedAction: 'Check gateway antenna orientation and interference sources.',
    aiGenerated: false,
    metadata: {
      affectedZone: 'West Zone'
    }
  },
  {
    id: 'ALT-2026-01106',
    severity: 'CRITICAL',
    type: 'Predicted Overflow',
    title: 'Critical Overflow Risk at Hospital Gate BIN-1004',
    description: 'BIN-1004 (Medical Waste Bin) at 94% fill, predicted overflow in 45 min.',
    source: 'AI Prediction',
    entityType: 'BIN',
    entityId: 'BIN-1004',
    location: 'City Hospital Emergency Gate',
    zone: 'Central Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '5 min ago',
    recommendedAction: 'Immediate hazardous/medical collection dispatch required.',
    aiGenerated: true,
    metadata: {
      currentFill: 94,
      predictedFill: 99,
      predictedOverflowTime: '45m',
      confidenceScore: 96,
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01107',
    severity: 'HIGH',
    type: 'Overdue Collection',
    title: 'Commercial District Bin Overdue by 3 hours',
    description: 'BIN-1190 collection missed morning deadline and reached 87% fill.',
    source: 'Admin/System',
    entityType: 'BIN',
    entityId: 'BIN-1190',
    location: 'Commercial Mall South',
    zone: 'East Zone',
    status: 'ACKNOWLEDGED',
    isRead: true,
    createdAt: '2h 15m ago',
    acknowledgedAt: '1h 30m ago',
    recommendedAction: 'Dispatch Route RT-019 to clear commercial mall bins.',
    aiGenerated: false,
    metadata: {
      currentFill: 87,
      affectedZone: 'East Zone'
    }
  },
  {
    id: 'ALT-2026-01108',
    severity: 'MEDIUM',
    type: 'Unusual Waste Pattern',
    title: 'Non-Recyclable Waste Spike in Recycling Bin',
    description: 'Optical classification camera detected high contamination rate at Bin BIN-1240.',
    source: 'AI Prediction',
    entityType: 'BIN',
    entityId: 'BIN-1240',
    location: 'University Green Quad',
    zone: 'North Zone',
    status: 'ACTIVE',
    isRead: false,
    createdAt: '2h 45m ago',
    recommendedAction: 'Dispatch sorting inspection team and post recycling guidance signage.',
    aiGenerated: true,
    metadata: {
      confidenceScore: 89,
      affectedZone: 'North Zone'
    }
  },
  {
    id: 'ALT-2026-01109',
    severity: 'LOW',
    type: 'Route Optimization Required',
    title: 'Route RT-015 Efficiency Drop',
    description: 'Travel time per bin collected on RT-015 increased by 18% due to road construction.',
    source: 'Route Engine',
    entityType: 'ROUTE',
    entityId: 'RT-015',
    location: 'Central Connector Road',
    zone: 'Central Zone',
    status: 'SNOOZED',
    isRead: true,
    createdAt: '4h 10m ago',
    snoozedUntil: 'Today 04:00 PM',
    recommendedAction: 'Re-run OR-Tools route optimization with updated road closure boundaries.',
    aiGenerated: true,
    metadata: {
      affectedZone: 'Central Zone'
    }
  },
  {
    id: 'ALT-2026-01110',
    severity: 'INFO',
    type: 'System Health Warning',
    title: 'Daily Fleet Telemetry Audit Completed',
    description: 'Automated health check verified 24 collection vehicles and 418 smart bins.',
    source: 'Admin/System',
    entityType: 'SYSTEM',
    entityId: 'SYS-AUDIT-26',
    location: 'Operations Center',
    zone: 'Central Zone',
    status: 'RESOLVED',
    isRead: true,
    createdAt: '7h ago',
    resolvedAt: '6h 30m ago',
    resolutionNote: 'Audit report archived.',
    recommendedAction: 'System operating normally.',
    aiGenerated: false,
    metadata: {
      affectedZone: 'Central Zone'
    }
  }
];

export interface AlertRuleItem {
  id: string;
  name: string;
  condition: string;
  enabled: boolean;
  severity: AlertSeverity;
}

export const initialAlertRules: AlertRuleItem[] = [
  { id: 'rule-1', name: 'Bin Fill > 90%', condition: 'Instant alert when bin ultrasonic reading exceeds 90%', enabled: true, severity: 'CRITICAL' },
  { id: 'rule-2', name: 'Predicted Overflow < 6h', condition: 'AI model projects threshold crossing within 6 hours', enabled: true, severity: 'CRITICAL' },
  { id: 'rule-3', name: 'Vehicle Capacity > 80%', condition: 'Payload scale reading exceeds 80% vehicle payload rating', enabled: true, severity: 'HIGH' },
  { id: 'rule-4', name: 'Route Delay > 15 min', condition: 'GPS tracker position lags schedule by more than 15 minutes', enabled: true, severity: 'HIGH' },
  { id: 'rule-5', name: 'Sensor Offline > 10 min', condition: 'No heartbeat packet received for 10 consecutive minutes', enabled: true, severity: 'MEDIUM' },
  { id: 'rule-6', name: 'Waste Generation > 20% Baseline', condition: 'Fill rate acceleration exceeds historical 7-day average by 20%', enabled: true, severity: 'MEDIUM' },
];
