"""add alerts and alert_activities tables

Revision ID: 8bae1eb2c0fe
Revises: 60c89eb43096
Create Date: 2026-09-19 21:13:07.041714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bae1eb2c0fe'
down_revision: Union[str, None] = '60c89eb43096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('alert_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('source', sa.String(length=50), server_default='System', nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ai_generated'), 'alerts', ['ai_generated'], unique=False)
    op.create_index(op.f('ix_alerts_alert_code'), 'alerts', ['alert_code'], unique=True)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity_type'), 'alerts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved_at'), 'alerts', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_snoozed_until'), 'alerts', ['snoozed_until'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_uuid'), 'alerts', ['uuid'], unique=True)
    op.create_index(op.f('ix_alerts_zone'), 'alerts', ['zone'], unique=False)
    op.create_table('alert_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_activities_alert_id'), 'alert_activities', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_activities_created_at'), 'alert_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_activities_id'), 'alert_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_activities_id'), table_name='alert_activities')
    op.drop_index(op.f('ix_alert_activities_created_at'), table_name='alert_activities')
    op.drop_index(op.f('ix_alert_activities_alert_id'), table_name='alert_activities')
    op.drop_table('alert_activities')
    op.drop_index(op.f('ix_alerts_zone'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_uuid'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_snoozed_until'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_code'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ai_generated'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
