"""add vehicle maintenance and activity history

Revision ID: 2c4237edb865
Revises: b01190cbc044
Create Date: 2026-09-19 15:48:31.202696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4237edb865'
down_revision: Union[str, None] = 'b01190cbc044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='maintenance_status_enum', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_records_id'), 'vehicle_maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_records_service_date'), 'vehicle_maintenance_records', ['service_date'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_records_status'), 'vehicle_maintenance_records', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_records_vehicle_id'), 'vehicle_maintenance_records', ['vehicle_id'], unique=False)
    op.create_table('vehicle_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_activities_activity_type'), 'vehicle_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_vehicle_activities_created_at'), 'vehicle_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_activities_id'), 'vehicle_activities', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_activities_vehicle_id'), 'vehicle_activities', ['vehicle_id'], unique=False)
    op.add_column('vehicles', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('energy_type', sa.Enum('DIESEL', 'CNG', 'ELECTRIC', 'HYBRID', name='vehicle_energy_type_enum', native_enum=False), server_default='DIESEL', nullable=False))
    op.add_column('vehicles', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('COMPACTOR', 'TIPPER', 'RECYCLING_TRUCK', 'MINI_COLLECTION', 'ELECTRIC_COLLECTION', name='vehicle_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('AVAILABLE', 'ON_ROUTE', 'IDLE', 'MAINTENANCE', 'OFFLINE', 'INACTIVE', name='vehicle_status_enum', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_is_active'), 'vehicles', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_vehicles_zone'), 'vehicles', ['zone'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_zone'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_active'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('AVAILABLE', 'ON_ROUTE', 'IDLE', 'MAINTENANCE', 'OFFLINE', 'INACTIVE', name='vehicle_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.Enum('COMPACTOR', 'TIPPER', 'RECYCLING_TRUCK', 'MINI_COLLECTION', 'ELECTRIC_COLLECTION', name='vehicle_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicles', 'last_location_update')
    op.drop_column('vehicles', 'current_longitude')
    op.drop_column('vehicles', 'current_latitude')
    op.drop_column('vehicles', 'driver_id')
    op.drop_column('vehicles', 'energy_type')
    op.drop_column('vehicles', 'registration_number')
    op.drop_index(op.f('ix_vehicle_activities_vehicle_id'), table_name='vehicle_activities')
    op.drop_index(op.f('ix_vehicle_activities_id'), table_name='vehicle_activities')
    op.drop_index(op.f('ix_vehicle_activities_created_at'), table_name='vehicle_activities')
    op.drop_index(op.f('ix_vehicle_activities_activity_type'), table_name='vehicle_activities')
    op.drop_table('vehicle_activities')
    op.drop_index(op.f('ix_vehicle_maintenance_records_vehicle_id'), table_name='vehicle_maintenance_records')
    op.drop_index(op.f('ix_vehicle_maintenance_records_status'), table_name='vehicle_maintenance_records')
    op.drop_index(op.f('ix_vehicle_maintenance_records_service_date'), table_name='vehicle_maintenance_records')
    op.drop_index(op.f('ix_vehicle_maintenance_records_id'), table_name='vehicle_maintenance_records')
    op.drop_table('vehicle_maintenance_records')
    # ### end Alembic commands ###
