"""add bin management sensors telemetry collections activity

Revision ID: fca64a770500
Revises: 2c4237edb865
Create Date: 2026-09-19 16:13:32.704613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca64a770500'
down_revision: Union[str, None] = '2c4237edb865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_activities_activity_type'), 'bin_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_bin_activities_bin_id'), 'bin_activities', ['bin_id'], unique=False)
    op.create_index(op.f('ix_bin_activities_created_at'), 'bin_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_bin_activities_id'), 'bin_activities', ['id'], unique=False)
    op.create_index(op.f('ix_bin_activities_performed_by'), 'bin_activities', ['performed_by'], unique=False)
    op.create_table('bin_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=True),
    sa.Column('fill_percentage', sa.Float(), nullable=False),
    sa.Column('fill_kg', sa.Float(), nullable=False),
    sa.Column('battery_percentage', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('connectivity_status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', name='connectivitystatus', native_enum=False), server_default='ONLINE', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), server_default='IOT', nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_telemetry_bin_id'), 'bin_telemetry', ['bin_id'], unique=False)
    op.create_index('ix_bin_telemetry_bin_id_recorded_at', 'bin_telemetry', ['bin_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_bin_telemetry_id'), 'bin_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_bin_telemetry_recorded_at'), 'bin_telemetry', ['recorded_at'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(length=50), server_default='ULTRASONIC', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('battery_percentage', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fill_reading', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('connectivity_status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', name='connectivitystatus', native_enum=False), server_default='ONLINE', nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_bin_id'), 'sensors', ['bin_id'], unique=True)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_id'), 'sensors', ['sensor_id'], unique=True)
    op.create_index(op.f('ix_sensors_uuid'), 'sensors', ['uuid'], unique=True)
    op.create_table('bin_collection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('collection_status', sa.String(length=50), server_default='COLLECTED', nullable=False),
    sa.Column('collected_fill_percentage', sa.Float(), nullable=False),
    sa.Column('collected_weight_kg', sa.Float(), nullable=False),
    sa.Column('waste_type', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_collection_history_bin_id'), 'bin_collection_history', ['bin_id'], unique=False)
    op.create_index(op.f('ix_bin_collection_history_collected_at'), 'bin_collection_history', ['collected_at'], unique=False)
    op.create_index(op.f('ix_bin_collection_history_collected_by'), 'bin_collection_history', ['collected_by'], unique=False)
    op.create_index(op.f('ix_bin_collection_history_id'), 'bin_collection_history', ['id'], unique=False)
    op.create_index(op.f('ix_bin_collection_history_route_id'), 'bin_collection_history', ['route_id'], unique=False)
    op.create_index(op.f('ix_bin_collection_history_vehicle_id'), 'bin_collection_history', ['vehicle_id'], unique=False)
    op.add_column('bins', sa.Column('bin_type', sa.Enum('STANDARD', 'RECYCLING', 'ORGANIC', 'COMMERCIAL', 'INDUSTRIAL', 'SMART', name='bintype', native_enum=False), server_default='STANDARD', nullable=False))
    op.add_column('bins', sa.Column('capacity_kg', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('bins', sa.Column('current_fill_kg', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('bins', sa.Column('current_fill_percentage', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('bins', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('bins', sa.Column('sensor_id', sa.String(length=50), nullable=True))
    op.add_column('bins', sa.Column('battery_percentage', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('bins', sa.Column('connectivity_status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', name='connectivitystatus', native_enum=False), server_default='ONLINE', nullable=False))
    op.add_column('bins', sa.Column('collection_status', sa.Enum('NOT_REQUIRED', 'SCHEDULED', 'PRIORITY', 'OVERDUE', 'IN_PROGRESS', 'COLLECTED', name='collectionstatus', native_enum=False), server_default='NOT_REQUIRED', nullable=False))
    op.add_column('bins', sa.Column('last_collection_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bins', sa.Column('next_collection_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bins', sa.Column('last_telemetry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bins', sa.Column('predicted_fill_percentage', sa.Float(), nullable=True))
    op.add_column('bins', sa.Column('predicted_overflow_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bins', sa.Column('prediction_confidence', sa.Float(), nullable=True))
    op.add_column('bins', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # Normalize legacy values in existing rows
    op.execute("UPDATE bins SET waste_type = 'OTHER' WHERE UPPER(waste_type) = 'MIXED'")
    op.execute("UPDATE bins SET waste_type = UPPER(waste_type) WHERE waste_type IN ('Plastic', 'Paper', 'Organic', 'Glass', 'Metal')")
    op.execute("UPDATE bins SET priority = 'LOW' WHERE UPPER(priority) = 'NORMAL'")
    op.execute("UPDATE bins SET priority = UPPER(priority)")
    op.execute("UPDATE bins SET capacity_kg = capacity_liters, current_fill_percentage = fill_level, current_fill_kg = (fill_level / 100.0) * capacity_liters")

    op.alter_column('bins', 'waste_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PLASTIC', 'PAPER', 'METAL', 'GLASS', 'ORGANIC', 'OTHER', name='wastetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('bins', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NORMAL', 'WARNING', 'CRITICAL', 'OFFLINE', 'MAINTENANCE', 'INACTIVE', 'ACTIVE', name='binstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('bins', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='collectionpriority', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_bins_bin_type'), 'bins', ['bin_type'], unique=False)
    op.create_index(op.f('ix_bins_collection_status'), 'bins', ['collection_status'], unique=False)
    op.create_index(op.f('ix_bins_connectivity_status'), 'bins', ['connectivity_status'], unique=False)
    op.create_index(op.f('ix_bins_current_fill_percentage'), 'bins', ['current_fill_percentage'], unique=False)
    op.create_index(op.f('ix_bins_is_active'), 'bins', ['is_active'], unique=False)
    op.create_index(op.f('ix_bins_last_telemetry_at'), 'bins', ['last_telemetry_at'], unique=False)
    op.create_index(op.f('ix_bins_predicted_overflow_at'), 'bins', ['predicted_overflow_at'], unique=False)
    op.create_index(op.f('ix_bins_priority'), 'bins', ['priority'], unique=False)
    op.create_index(op.f('ix_bins_sensor_id'), 'bins', ['sensor_id'], unique=True)
    op.create_index(op.f('ix_bins_status'), 'bins', ['status'], unique=False)
    op.create_index(op.f('ix_bins_waste_type'), 'bins', ['waste_type'], unique=False)
    op.create_index(op.f('ix_bins_zone'), 'bins', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bins_zone'), table_name='bins')
    op.drop_index(op.f('ix_bins_waste_type'), table_name='bins')
    op.drop_index(op.f('ix_bins_status'), table_name='bins')
    op.drop_index(op.f('ix_bins_sensor_id'), table_name='bins')
    op.drop_index(op.f('ix_bins_priority'), table_name='bins')
    op.drop_index(op.f('ix_bins_predicted_overflow_at'), table_name='bins')
    op.drop_index(op.f('ix_bins_last_telemetry_at'), table_name='bins')
    op.drop_index(op.f('ix_bins_is_active'), table_name='bins')
    op.drop_index(op.f('ix_bins_current_fill_percentage'), table_name='bins')
    op.drop_index(op.f('ix_bins_connectivity_status'), table_name='bins')
    op.drop_index(op.f('ix_bins_collection_status'), table_name='bins')
    op.drop_index(op.f('ix_bins_bin_type'), table_name='bins')
    op.alter_column('bins', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='collectionpriority', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('bins', 'status',
               existing_type=sa.Enum('NORMAL', 'WARNING', 'CRITICAL', 'OFFLINE', 'MAINTENANCE', 'INACTIVE', 'ACTIVE', name='binstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('bins', 'waste_type',
               existing_type=sa.Enum('PLASTIC', 'PAPER', 'METAL', 'GLASS', 'ORGANIC', 'OTHER', name='wastetype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('bins', 'is_active')
    op.drop_column('bins', 'prediction_confidence')
    op.drop_column('bins', 'predicted_overflow_at')
    op.drop_column('bins', 'predicted_fill_percentage')
    op.drop_column('bins', 'last_telemetry_at')
    op.drop_column('bins', 'next_collection_at')
    op.drop_column('bins', 'last_collection_at')
    op.drop_column('bins', 'collection_status')
    op.drop_column('bins', 'connectivity_status')
    op.drop_column('bins', 'battery_percentage')
    op.drop_column('bins', 'sensor_id')
    op.drop_column('bins', 'address')
    op.drop_column('bins', 'current_fill_percentage')
    op.drop_column('bins', 'current_fill_kg')
    op.drop_column('bins', 'capacity_kg')
    op.drop_column('bins', 'bin_type')
    op.drop_index(op.f('ix_bin_collection_history_vehicle_id'), table_name='bin_collection_history')
    op.drop_index(op.f('ix_bin_collection_history_route_id'), table_name='bin_collection_history')
    op.drop_index(op.f('ix_bin_collection_history_id'), table_name='bin_collection_history')
    op.drop_index(op.f('ix_bin_collection_history_collected_by'), table_name='bin_collection_history')
    op.drop_index(op.f('ix_bin_collection_history_collected_at'), table_name='bin_collection_history')
    op.drop_index(op.f('ix_bin_collection_history_bin_id'), table_name='bin_collection_history')
    op.drop_table('bin_collection_history')
    op.drop_index(op.f('ix_sensors_uuid'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_bin_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_bin_telemetry_recorded_at'), table_name='bin_telemetry')
    op.drop_index(op.f('ix_bin_telemetry_id'), table_name='bin_telemetry')
    op.drop_index('ix_bin_telemetry_bin_id_recorded_at', table_name='bin_telemetry')
    op.drop_index(op.f('ix_bin_telemetry_bin_id'), table_name='bin_telemetry')
    op.drop_table('bin_telemetry')
    op.drop_index(op.f('ix_bin_activities_performed_by'), table_name='bin_activities')
    op.drop_index(op.f('ix_bin_activities_id'), table_name='bin_activities')
    op.drop_index(op.f('ix_bin_activities_created_at'), table_name='bin_activities')
    op.drop_index(op.f('ix_bin_activities_bin_id'), table_name='bin_activities')
    op.drop_index(op.f('ix_bin_activities_activity_type'), table_name='bin_activities')
    op.drop_table('bin_activities')
    # ### end Alembic commands ###
