"""refactor_user_role_status_name_fields

Revision ID: ae771f5363fd
Revises: 9762074ce5e0
Create Date: 2026-09-19 15:08:12.659671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae771f5363fd'
down_revision: Union[str, None] = '9762074ce5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='platform_user_status', native_enum=False), nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'DRIVER', 'ANALYST', name='user_role_enum'),
               type_=sa.Enum('ADMIN', 'COLLECTOR', 'VIEWER', name='platform_user_role', native_enum=False),
               postgresql_using="CASE WHEN role::text = 'DRIVER' THEN 'COLLECTOR' WHEN role::text = 'ANALYST' THEN 'VIEWER' ELSE 'ADMIN' END",
               existing_nullable=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'COLLECTOR', 'VIEWER', name='platform_user_role', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'DRIVER', 'ANALYST', name='user_role_enum'),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'status')
    op.drop_column('users', 'department')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
