"""add waste classification table and indexes

Revision ID: 60c89eb43096
Revises: 3d849204e112
Create Date: 2026-09-19 19:43:57.542607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c89eb43096'
down_revision: Union[str, None] = '3d849204e112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('waste_type', sa.Enum('PLASTIC', 'PAPER', 'METAL', 'GLASS', 'ORGANIC', 'OTHER', name='wastetype', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='IMAGE', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('image_reference', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_low_confidence', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['bin_collection_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_classifications_bin_id'), 'waste_classifications', ['bin_id'], unique=False)
    op.create_index(op.f('ix_waste_classifications_classified_at'), 'waste_classifications', ['classified_at'], unique=False)
    op.create_index(op.f('ix_waste_classifications_collection_id'), 'waste_classifications', ['collection_id'], unique=False)
    op.create_index(op.f('ix_waste_classifications_id'), 'waste_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_waste_classifications_is_low_confidence'), 'waste_classifications', ['is_low_confidence'], unique=False)
    op.create_index(op.f('ix_waste_classifications_source'), 'waste_classifications', ['source'], unique=False)
    op.create_index(op.f('ix_waste_classifications_uuid'), 'waste_classifications', ['uuid'], unique=True)
    op.create_index(op.f('ix_waste_classifications_waste_type'), 'waste_classifications', ['waste_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_classifications_waste_type'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_uuid'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_source'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_is_low_confidence'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_id'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_collection_id'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_classified_at'), table_name='waste_classifications')
    op.drop_index(op.f('ix_waste_classifications_bin_id'), table_name='waste_classifications')
    op.drop_table('waste_classifications')
    # ### end Alembic commands ###
