"""add_planning_module_tables

Revision ID: 86534281b4a0
Revises: 3d849204e112
Create Date: 2026-09-19 20:57:22.183135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86534281b4a0'
down_revision: Union[str, None] = '3d849204e112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_windows_id'), 'collection_windows', ['id'], unique=False)
    op.create_index(op.f('ix_collection_windows_name'), 'collection_windows', ['name'], unique=True)
    op.create_table('planning_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_vehicle_utilization', sa.Float(), nullable=False),
    sa.Column('max_route_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_stops', sa.Integer(), nullable=False),
    sa.Column('respect_collection_windows', sa.Boolean(), nullable=False),
    sa.Column('distance_weight', sa.Integer(), nullable=False),
    sa.Column('capacity_weight', sa.Integer(), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('time_weight', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_constraints_id'), 'planning_constraints', ['id'], unique=False)
    op.create_table('collection_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('planning_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.Enum('TODAY', 'NEXT_12_HOURS', 'NEXT_24_HOURS', 'NEXT_48_HOURS', 'NEXT_7_DAYS', name='plan_horizon_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATING', 'READY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='plan_status_enum', native_enum=False), nullable=False),
    sa.Column('strategy', sa.Enum('SHORTEST_DISTANCE', 'MINIMUM_TIME', 'MAX_CAPACITY_UTILIZATION', 'BALANCED', name='plan_strategy_enum', native_enum=False), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('total_bins', sa.Integer(), nullable=False),
    sa.Column('assigned_bins', sa.Integer(), nullable=False),
    sa.Column('unassigned_bins', sa.Integer(), nullable=False),
    sa.Column('estimated_waste_kg', sa.Float(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('average_vehicle_utilization', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_plans_created_by_id'), 'collection_plans', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_collection_plans_id'), 'collection_plans', ['id'], unique=False)
    op.create_index(op.f('ix_collection_plans_plan_code'), 'collection_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_collection_plans_planning_date'), 'collection_plans', ['planning_date'], unique=False)
    op.create_index(op.f('ix_collection_plans_status'), 'collection_plans', ['status'], unique=False)
    op.create_index(op.f('ix_collection_plans_uuid'), 'collection_plans', ['uuid'], unique=True)
    op.create_table('collection_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('estimated_waste_kg', sa.Float(), nullable=False),
    sa.Column('current_fill_percentage', sa.Float(), nullable=False),
    sa.Column('predicted_fill_percentage', sa.Float(), nullable=False),
    sa.Column('predicted_overflow', sa.Boolean(), nullable=False),
    sa.Column('prediction_confidence', sa.Float(), nullable=False),
    sa.Column('collection_window', sa.String(length=50), nullable=False),
    sa.Column('assignment_status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'COLLECTED', 'SKIPPED', name='plan_item_assignment_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_plan_items_assignment_status'), 'collection_plan_items', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_collection_plan_items_bin_id'), 'collection_plan_items', ['bin_id'], unique=False)
    op.create_index(op.f('ix_collection_plan_items_id'), 'collection_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_collection_plan_items_plan_id'), 'collection_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_collection_plan_items_zone'), 'collection_plan_items', ['zone'], unique=False)
    op.create_table('collection_plan_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('planned_load_kg', sa.Float(), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('planned_stops', sa.Integer(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('assignment_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_plan_vehicles_driver_id'), 'collection_plan_vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_collection_plan_vehicles_id'), 'collection_plan_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_collection_plan_vehicles_plan_id'), 'collection_plan_vehicles', ['plan_id'], unique=False)
    op.create_index(op.f('ix_collection_plan_vehicles_vehicle_id'), 'collection_plan_vehicles', ['vehicle_id'], unique=False)
    op.create_table('planning_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VEHICLE_CAPACITY', 'DRIVER_CONFLICT', 'VEHICLE_UNAVAILABLE', 'DRIVER_UNAVAILABLE', 'DUPLICATE_BIN', 'DURATION_LIMIT', 'STOP_LIMIT', 'WASTE_COMPATIBILITY', 'COLLECTION_WINDOW', 'ZONE_CONFLICT', 'UNASSIGNED_PRIORITY', 'UTILIZATION_LIMIT', 'OTHER', name='planning_conflict_type_enum', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='planning_conflict_severity_enum', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_conflicts_id'), 'planning_conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_planning_conflicts_plan_id'), 'planning_conflicts', ['plan_id'], unique=False)
    op.create_table('planning_route_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_load_kg', sa.Float(), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_route_proposals_driver_id'), 'planning_route_proposals', ['driver_id'], unique=False)
    op.create_index(op.f('ix_planning_route_proposals_id'), 'planning_route_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_planning_route_proposals_plan_id'), 'planning_route_proposals', ['plan_id'], unique=False)
    op.create_index(op.f('ix_planning_route_proposals_vehicle_id'), 'planning_route_proposals', ['vehicle_id'], unique=False)
    op.create_table('planning_route_proposal_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.String(length=50), nullable=True),
    sa.Column('estimated_collection_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['planning_route_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_route_proposal_stops_bin_id'), 'planning_route_proposal_stops', ['bin_id'], unique=False)
    op.create_index(op.f('ix_planning_route_proposal_stops_id'), 'planning_route_proposal_stops', ['id'], unique=False)
    op.create_index(op.f('ix_planning_route_proposal_stops_proposal_id'), 'planning_route_proposal_stops', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_route_proposal_stops_proposal_id'), table_name='planning_route_proposal_stops')
    op.drop_index(op.f('ix_planning_route_proposal_stops_id'), table_name='planning_route_proposal_stops')
    op.drop_index(op.f('ix_planning_route_proposal_stops_bin_id'), table_name='planning_route_proposal_stops')
    op.drop_table('planning_route_proposal_stops')
    op.drop_index(op.f('ix_planning_route_proposals_vehicle_id'), table_name='planning_route_proposals')
    op.drop_index(op.f('ix_planning_route_proposals_plan_id'), table_name='planning_route_proposals')
    op.drop_index(op.f('ix_planning_route_proposals_id'), table_name='planning_route_proposals')
    op.drop_index(op.f('ix_planning_route_proposals_driver_id'), table_name='planning_route_proposals')
    op.drop_table('planning_route_proposals')
    op.drop_index(op.f('ix_planning_conflicts_plan_id'), table_name='planning_conflicts')
    op.drop_index(op.f('ix_planning_conflicts_id'), table_name='planning_conflicts')
    op.drop_table('planning_conflicts')
    op.drop_index(op.f('ix_collection_plan_vehicles_vehicle_id'), table_name='collection_plan_vehicles')
    op.drop_index(op.f('ix_collection_plan_vehicles_plan_id'), table_name='collection_plan_vehicles')
    op.drop_index(op.f('ix_collection_plan_vehicles_id'), table_name='collection_plan_vehicles')
    op.drop_index(op.f('ix_collection_plan_vehicles_driver_id'), table_name='collection_plan_vehicles')
    op.drop_table('collection_plan_vehicles')
    op.drop_index(op.f('ix_collection_plan_items_zone'), table_name='collection_plan_items')
    op.drop_index(op.f('ix_collection_plan_items_plan_id'), table_name='collection_plan_items')
    op.drop_index(op.f('ix_collection_plan_items_id'), table_name='collection_plan_items')
    op.drop_index(op.f('ix_collection_plan_items_bin_id'), table_name='collection_plan_items')
    op.drop_index(op.f('ix_collection_plan_items_assignment_status'), table_name='collection_plan_items')
    op.drop_table('collection_plan_items')
    op.drop_index(op.f('ix_collection_plans_uuid'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_status'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_planning_date'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_plan_code'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_id'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_created_by_id'), table_name='collection_plans')
    op.drop_table('collection_plans')
    op.drop_index(op.f('ix_planning_constraints_id'), table_name='planning_constraints')
    op.drop_table('planning_constraints')
    op.drop_index(op.f('ix_collection_windows_name'), table_name='collection_windows')
    op.drop_index(op.f('ix_collection_windows_id'), table_name='collection_windows')
    op.drop_table('collection_windows')
    # ### end Alembic commands ###
