from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class BaseAlertSchema(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True,
    )


class AlertActivityItem(BaseAlertSchema):
    timestamp: str
    description: str
    actor: Optional[str] = None
    action: Optional[str] = None
    note: Optional[str] = None


class AlertCreate(BaseAlertSchema):
    title: str = Field(..., max_length=255, description="Alert headline/summary")
    description: str = Field(..., description="Detailed description or message")
    category: str = Field(default="BIN", description="Operational category: BIN, VEHICLE, ROUTE, SENSOR, PREDICTION, etc.")
    severity: str = Field(default="WARNING", description="Severity level: CRITICAL, HIGH, MEDIUM, LOW, INFO")
    source: str = Field(default="System", description="Source of alert: AI Prediction, Sensor, Vehicle System, Admin/System, etc.")
    entity_type: str = Field(default="BIN", description="Affected entity: BIN, VEHICLE, ROUTE, ZONE, SENSOR, SYSTEM")
    entity_id: str = Field(..., description="ID or code of affected entity (e.g. BIN-1087, VH-004)")
    location: Optional[str] = Field(None, description="Human-readable physical location")
    zone: Optional[str] = Field(None, description="Operational zone (e.g. Central Zone)")
    recommended_action: Optional[str] = Field(None, description="Actionable recommendation for operators")
    ai_generated: bool = Field(default=False, description="Flag indicating if alert was generated by AI model")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Contextual telemetry / prediction metadata")


class AlertUpdate(BaseAlertSchema):
    title: Optional[str] = None
    description: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    recommended_action: Optional[str] = None
    assigned_to: Optional[str] = None
    is_read: Optional[bool] = None


class AcknowledgeAlertRequest(BaseAlertSchema):
    acknowledged_by: Optional[str] = Field(None, description="Operator name or identifier")
    note: Optional[str] = Field(None, description="Optional operator note")


class ResolveAlertRequest(BaseAlertSchema):
    resolution_note: Optional[str] = Field("Resolved by operational dispatch", description="Explanation of resolution")
    resolved_by: Optional[str] = Field(None, description="Operator name or identifier")
    note: Optional[str] = Field(None, description="Optional alias for resolution_note")


class SnoozeAlertRequest(BaseAlertSchema):
    snooze_until: Optional[str] = Field("1 hour", description="Future ISO timestamp or duration string (e.g. '1 hour', '4 hours', 'tomorrow')")
    note: Optional[str] = Field(None, description="Optional snooze note")


class BulkAlertActionRequest(BaseAlertSchema):
    alert_ids: List[Union[str, int]] = Field(..., description="List of alert IDs or alert codes to process")
    action: str = Field(..., description="Action to execute: 'read', 'acknowledge', 'resolve', 'snooze'")
    payload: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Optional parameters such as 'note' or 'duration'")
    note: Optional[str] = Field(None, description="Optional note")


class AlertItemResponse(BaseAlertSchema):
    id: str
    internal_id: int
    alert_code: Optional[str] = None
    severity: str
    category: Optional[str] = None
    type: str
    title: str
    description: str
    source: str
    entity_type: str
    entity_id: str
    location: str
    zone: str
    status: str
    is_read: bool
    created_at: str
    acknowledged_at: Optional[str] = None
    acknowledged_by: Optional[str] = None
    resolved_at: Optional[str] = None
    resolved_by: Optional[str] = None
    snoozed_until: Optional[str] = None
    resolution_note: Optional[str] = None
    recommended_action: Optional[str] = None
    ai_generated: bool
    metadata: Dict[str, Any] = Field(default_factory=dict)
    activity_log: List[AlertActivityItem] = Field(default_factory=list)


class AlertListResponse(BaseAlertSchema):
    items: List[AlertItemResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


class AlertSummaryResponse(BaseAlertSchema):
    active: int
    critical: int
    unacknowledged: int
    resolved_today: int
    ai_alerts: int
    unread: int
    total: int


class AlertTrendItem(BaseAlertSchema):
    day: str
    critical: int
    high: int
    medium: int
    low: int


class AlertTrendsResponse(BaseAlertSchema):
    trends: List[AlertTrendItem]


class AlertCategoryItem(BaseAlertSchema):
    name: str
    count: int
    percent: int
    percentage: Optional[int] = None


class AlertCategoriesResponse(BaseAlertSchema):
    categories: List[AlertCategoryItem]
